api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
    path('house/', views.houselist, name='houselist'),
    path('house/<ident>', views.housedetail, name='housedetail'),
    path('house/<ident>/', views.housedetail, name='housedetail'),
    path('house/<ident>/bills', views.housebills, name='housebills'),
    path('bill/', views.billlist, name='billlist'),
    path('bill/<house>/<number>', views.billdetail, name='billdetail'),
    path('bill/<name>/', views.billdetail, name='billdetail')
]

bills/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'bills'

urlpatterns = [
    path('', views.index, name='index'),
    path('bill/', views.BillsListView.as_view(), name='list'),
    path('bill/<pk>/', views.BillDetailView.as_view(), name='detail'),
    path('house/', views.HouseListView.as_view(), name='houselist'),
    path('house/<pk>/', views.housedetail, name='housedetail'),
    path('bill/<pk>/edit', login_required(views.BillUpdateView.as_view()), name='billupdate'),
    path('bill/add', login_required(views.BillCreateView.as_view()), name='billcreate'),
    path('house/add', login_required(views.HouseCreateView.as_view()), name='housecreate'),
    path('house/<pk>/edit', login_required(views.HouseUpdateView.as_view()), name='houseupdate'),
    path('bill/<pk>/delete', login_required(views.BillDeleteView.as_view()), name='billdelete'),
    path('house/<pk>/delete', login_required(views.HouseDeleteView.as_view()), name='housedelete'),
    path('bill/search', views.BillSearchListView.as_view(), name='billsearch'),
    path('guide/', login_required(views.guide), name='guide'),
]

legislation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bills.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('api/', include('api.urls')),
]

bills/models.py
from django.db import models


class House(models.Model):
    house_name = models.CharField(max_length=100)
    house_code = models.CharField(max_length=2)
    logo_url = models.URLField(default="https://einfon.com/wp-content/uploads/2017/05/Flag-Of-USA.jpg")

    def __str__(self):
        return self.house_name + " - " + self.house_code


class Bill(models.Model):
    bill_number = models.IntegerField()
    bill_name = models.CharField(max_length=250)
    bill_house = models.ForeignKey(House, on_delete=models.CASCADE, default=1)
    bill_content = models.TextField()
    date_first_posted = models.DateField()

    def __str__(self):
        return self.bill_house.house_code + '. ' + str(self.bill_number) + ' - ' + self.bill_name

bills/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.db.models import Q

from .models import Bill, House


class BillsListView(generic.ListView):
    model = Bill
    template_name = 'bills/list.html'


class BillDetailView(generic.DetailView):
    model = Bill
    template_name = 'bills/detail.html'


def index(request):
    return HttpResponse(render(request, 'bills/index.html'))


class HouseListView(generic.ListView):
    model = House
    template_name = 'bills/houselist.html'


def housedetail(request, pk):
    house = get_object_or_404(House.objects.filter(pk=pk))
    bill_list = Bill.objects.filter(bill_house=house)
    bill_count = bill_list.count()
    context = {
        'house': house,
        'bill_list': bill_list,
        'bill_count': bill_count,
    }
    return render(request, 'bills/housedetail.html', context)


class BillUpdateView(generic.UpdateView):
    model = Bill
    template_name = 'bills/update.html'
    fields = [
        'bill_number',
        'bill_name',
        'bill_house',
        'bill_content',
        'date_first_posted',
    ]

    def form_valid(self, form):
        bill = form.save()
        return redirect('bills:detail', pk=bill.pk)


class BillCreateView(generic.CreateView):
    model = Bill
    template_name = 'bills/create.html'
    fields = [
        'bill_number',
        'bill_name',
        'bill_house',
        'bill_content',
        'date_first_posted',
    ]

    def form_valid(self, form):
        bill = form.save()
        return redirect('bills:detail', pk=bill.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'bill'
        return context


class HouseCreateView(generic.CreateView):
    model = House
    template_name = 'bills/create.html'
    fields = [
        'house_name',
        'house_code',
        'logo_url',
    ]

    def form_valid(self, form):
        bill = form.save()
        return redirect('bills:housedetail', pk=bill.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'house'
        return context


class HouseUpdateView(generic.UpdateView):
    model = House
    template_name = 'bills/update.html'
    fields = [
        'house_name',
        'house_code',
        'logo_url',
    ]

    def form_valid(self, form):
        bill = form.save()
        return redirect('bills:housedetail', pk=bill.pk)


class BillDeleteView(generic.DeleteView):
    model = Bill
    success_url = reverse_lazy('bills:list')


class HouseDeleteView(generic.DeleteView):
    model = House
    success_url = reverse_lazy('bills:houselist')


class BillSearchListView(generic.ListView):
    model = Bill
    template_name = 'bills/billsearch.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        result = Bill.objects.filter(Q(bill_name__contains=query) | Q(bill_content__contains=query)
                                     | Q(bill_number__contains=query))
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        return context


def guide(request):
    return render(request, 'bills/guide.html')

bills/templates/bills/bill_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deleting {{ bill.bill_name }}</title>
</head>
<body>
     {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top: 12px;" align="center">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ bill.bill_name }}"?</p>
            <p>This action <strong>cannot be undone</strong>.</p>
            <p></p>
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
    </div>
</body>
</html>

bills/templates/bills/billsearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bills List</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top:12px;">
    <h1 style="display: inline;">Search results&nbsp;&nbsp;</h1>
        <h4 style="display: inline;">Searching for "<strong>{{ query }}</strong>"</h4>
        <p>This search looks through both titles and content.</p>
    {% if bill_list %}
    <div class="table-responsive table-bordered table-hover">
        <table class="table" style="margin-bottom: 0px;">
            <thead class="thead-light">
                <tr>
                    <th style="width:80%;">Name</th>
                    <th>Year</th>
                </tr>
            </thead>
            <tbody>
                {% for bill in bill_list %}
                <tr>
                    <td><a href="{% url 'bills:detail' bill.pk %}">{{ bill.bill_house.house_code }}. {{ bill.bill_number|stringformat:"03d" }} - {{ bill.bill_name }}</a></td>
                    <td>{{ bill.date_first_posted.year }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <p>There were no search results.</p>
    {% endif %}
    </div>
</body>
</html>

bills/templates/bills/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add {{ type }} - ModelUSGov Archives</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <!--{ if user.is_authenticated }-->
    <div class="container" style="margin-top: 12px;" align="center">
        <h2>Adding {{ type }}</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" style="background-color:#e6eaed;color:rgb(0,0,0);" value="Save">
        </form>
    </div>
    <!--ELSE-->
        <!--<meta http-equiv="REFRESH" content="0;url='/accounts/login'">-->
    <!--ENDIF-->
</body>
</html>

bills/templates/bills/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ bill.bill_house.house_code }}. {{ bill.bill_number|stringformat:"03d" }} - {{ bill.bill_name }}</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top: 12px;">
    {% if user.is_authenticated %}<p style="display: inline; float: right;"><a href="{% url 'bills:billupdate' bill.pk %}">Edit bill</a></p>{% endif %}
    <h1><strong>{{ bill.bill_house.house_code }}. {{ bill.bill_number|stringformat:"03d" }} - {{ bill.bill_name }}</strong></h1>
    <p>
        {{ bill.bill_content|linebreaks }}
    </p>
        <hr>
        <p>This bill was first posted on {{ bill.date_first_posted }}.</p>
    </div>
</body>
</html>

bills/templates/bills/guide.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Archive Guide</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top:12px;" align>
    <h1>Archive Guide</h1>
    <p>Welcome to the ModelUSGov Legislation Archives! If you can see this page, you already have a valid Archive acount, and should be ready to go. This guide explains how the Archive works, how to use it, and the best practices. Please have a quick read through
        before you start! If you need to link to a specific section of this guide, use the blue hashtags.</p>
    <h4 id="accounts" style="display: inline-block;">Archive accounts</h4>&nbsp;<a style="color: #3BB9FF;" href="#accounts">#</a>
    <p>The Archive is publicly accessible. Anybody with an internet connection can see every bill and resolution stored here. However, to be able to add, edit and delete items, you need to have an Archive account. Accounts should only be used by the person
        for whom they are intended.</p>
    <p>Accounts can only be made and deleted by admins. Once your account is created, an admin will send you your login details. You can then change your password. While all passwords are encrypted, we recommend not using the same password as your Reddit
        account. If you need your password to be reset, or to change your username, you need to contact an admin.<br /></p>
    <h4 id="admins" style="display: inline-block;">Admins</h4>&nbsp;<a style="color: #3BB9FF;" href="#admins">#</a>
    <p>Some Archive accounts have access to the admin panel. This allows them to access the archive databases. This access is usually only given to whoever maintains the archive and the Head Mod. However, admin rights can be granted to any account by an
        admin on a temporary or permanent basis. This will only be done when there is a need. While all accounts with admin rights have access to the panel, they do not necessarily have access to all of the features, so restricted access can be granted
        if required. The admin panel can be customised by a superuser to suit individual admins&#39; needs.<br /></p>
    <p>The <em>superusers</em> are the people who maintain the back-end of the archive and can edit the code. They have automatic access to every permission and cannot be restricted. Superusers are admins with special abilities, so they can be contacted like
        other admins. This role is only given to those who are working on the code or the server. Currently there is one superuser: KeelanD. Any technical issues or bugs should be reported to a superuser.<br /></p>
    <h4 id="permissions" style="display: inline-block;">Permissions</h4>&nbsp;<a style="color: #3BB9FF;" href="#permissions">#</a>
    <p>All Archive accounts can add, edit, and delete bills, resolutions and houses. It is required, though, that when deleting a house, a user has the approval of an admin, since this will delete all bills associated with that house. Certain permissions,
        such as the ability to delete items, may be revoked.</p>
    <h4 id="login" style="display: inline-block;">Logging in and out</h4>&nbsp;<a style="color: #3BB9FF;" href="#login">#</a>
    <p>To log in, you click on the button in the top-right corner of the website if the button says &quot;Log in.&quot; You will be taken to a page where you can input your username and password. If your credentials are correct, you will be redirected to
        the page you were on before you clicked the log in button. Be aware that logging out while adding or editing an item will remove your progress unless you click the save button. If you have admin rights, you can also log in by going to the admin
        panel. Once you log in on either the main Archive or the admin panel, you will be logged in on both, and the same for logging out. Archive accounts without admin rights are not able to log in using the admin panel.</p>
    <p>If you try to access any page that requires you to be logged in, such as edit pages, you will be taken to the log in page. After logging in, you should be redirected back to the page you were trying to access.</p>
    <h4 id="items" style="display: inline-block;">Items</h4>&nbsp;<a style="color: #3BB9FF;" href="#items">#</a>
    <p>The individual documents (bills and resolutions) and the houses are known as &quot;items.&quot; Every item has fields specific to its type, all of which must be filled out. These fields are the essential information about that item. For example, some
        of the fields for a bill include its name and its content. The Archive won&#39;t let you add or edit an item unless all of the fields are filled. Individual fields are explained in each item&#39;s section of this guide.</p>
    <h4 id="houses" style="display: inline-block;">Houses</h4>&nbsp;<a style="color: #3BB9FF;" href="#houses">#</a>
    <p>The houses are the seven legislative chambers in ModelUSGov: the five state assemblies, the House of Representatives, and the Senate. Houses can be removed or added as necessary, like when states are added or abolished. All bills and resolutions must
        be assigned a house - i.e. the house in which it was first submitted. Houses should not be deleted without admin approval.</p>
    <p>Each house has three fields, described below:<br /><strong>House name</strong> This is the official name of the house. You should not use abbreviations here.<br /><strong>House code</strong> This is the one- or two-letter code for the House. The code appears in
        the bill identifier, e.g.<strong>HR</strong>.021, where HR is the two-letter code for the House of Representatives. To avoid ambiguity, state codes are the first letter of the cardinal direction, followed by the letter &quot;S&quot; for state,
        with the exception of the Northeastern State, which is &quot;NE.&quot; This is despite the fact that most states use identifiers like <strong>B.021</strong> for their bills.<br /><strong>Logo url</strong> This is the url to the image file which contains
        the seal or flag of the state. It is recommended that you first upload the image to an image host like <a href="//imgur.com">Imgur</a>, instead of using Reddit-hosted files. By default, the logo is set to the United States flag for newly-created
        houses.</p>
    <h4 id="bills" style="display: inline-block;">Bills</h4>&nbsp;<a style="color: #3BB9FF;" href="#bills">#</a>
    <p>Bills are the individual pieces of legislation from ModelUSGov. Each should be archived in its final form - i.e. with all successful amendents added, if necessary. However, amendments from future bills should <strong>not</strong> be added to the original.
        All bills, not just successful ones, should be archived. Bills should not be archived in Reddit format, and HTML tags will not work. (<em>Note: we are working on this.</em>)</p>
    <p>Each bill has five fields, described below:<br /><strong>Bill number</strong> This is the number part of a bill&#39;s identifier, e.g. HR.<strong>021</strong> or S.<strong>1004</strong>. You may include leading zeros, but they are not necessary, as the Archive
        will add them automatically.<br /><strong>Bill name</strong> This is the name of the bill. You should not include the year. Regardless of whether the bill was successful, its name should end with the word &quot;Bill&quot; - you should replace &quot;Act&quot;
        with &quot;Bill&quot; where applicable. For punctuation and spelling, follow the original title as posted on Reddit. Don&#39;t correct any spelling mistakes, punctuation errors or grammatical errors.<br /><strong>Bill house</strong> This is the house
        in which the bill was first posted. You are only able to pick from a dropdown list for this field. If the house you need isn&#39;t there, you may need to create it, or contact an admin.<br /><strong>Bill content</strong> This is the text of the bill.
        Follow the guidelines above about formatting and amendments. If copying and pasting directly from Reddit, ensure that the format matches the standard for other bills in that house. Like with the name, don&#39;t correct spelling, punctuation or
        grammar.<br /><strong>Date first posted</strong> This is the date on which the bill was first posted on Reddit. This is not the date it was submitted. To avoid database errors, it should be formatted YYYY-MM-DD. (<em>Note: We will add a date selector in the future.</em>)
        All dates are in <strong>Eastern Standard Time</strong> only. If you are living outside that timezone, please convert the date into EST. E.g. if you live in the UK and Reddit says it was posted at 2 am GMT on July 5th 2018, you should actually record
        this as July 4th 2018, since in EST, it&#39;s 9 pm on July 4th. This is not essential information, and the earliest date available should be recorded if you can&#39;t find the first date.</p>
    <h4 id="resolutions" style="display: inline-block;">Resolutions</h4>&nbsp;<a style="color: #3BB9FF;" href="#resolutions">#</a>
    <p>Resolutions are not available yet on the Archive, but you can expect that they will have the same fields as bills.</p>
    <h4 id="structure" style="display: inline-block;">Archive structure</h4>&nbsp;<a style="color: #3BB9FF;" href="#structure">#</a>
    <p>The archive currently has three archive pages: the Houses page, the Bills page, and the Resolutions page. The House page provides a list of all houses. Clicking on any of the names will send you to a page that gives details about the house and a list
        of all the bills and resolutions associated with it. Clicking on any of these will bring you to a page with the bill&#39;s or resolution&#39;s text. The Bills page provides you with a list of all bills, along with the year they were published.
        Clicking on any of the names will bring you to the same page with its text. The Resolutions page is similar to the Bills page, but instead it gives a list of resolutions.</p>
    <h4 id="adding" style="display: inline-block;">Adding items</h4>&nbsp;<a style="color: #3BB9FF;" href="#adding">#</a>
    <p>To add an item, you should go onto the list page for that item. There, if you are logged in, you will see a blue link in the top right. If you click on this, you will be brought to a page where you input the information into the fields. When you are
        finished, click the &quot;save&quot; button. The Archive will validate all the information you submitted and then upload it to the database. Within a second or two, you should be redirected to the individual page for the item you have just added.
        If any information is missing, or not formatted correctly, you will be prompted to fix it. Once taken to the new page, you should briefly read over it to ensure everything was processed correctly.</p>
    <h4 id="editing" style="display: inline-block;">Editing items</h4>&nbsp;<a style="color: #3BB9FF;" href="#editing">#</a>
    <p>To edit an item, you should go to the individual page for that item. There, if you are logged in, you will see a blue link in the top right. If you click on this, you will be brought to a page similar to the &quot;add&quot; page, but with the fields
        already filled with the information. You can edit any of the fields, and press the &quot;Save&quot; button once you are finished. The Archive will validate all the information you submitted and then upload it to the database. Within a second or
        two, you should be redirected to the individual page for the item you have just added. If any information is missing, or not formatted correctly, you will be prompted to fix it. Once taken to the new page, you should briefly read over it to ensure
        everything was processed correctly.<br /></p>
    <h4 id="deleting" style="display: inline-block;">Deleting items</h4>&nbsp;<a style="color: #3BB9FF;" href="#deleting">#</a>
    <p>To delete an item, you need to go to the edit page for the item. At the bottom, you will see a red link. Once you click this, you will be asked to confirm. Please read over the warnings provided to see if any apply in this case. If you&#39;re satisfied
        that it is okay to delete the item, then you may click the red &quot;Confirm&quot; button. After that, you will be taken to list page for that item. We recommend you confirm the item was successfully deleted by either searching for it in the search
        box, looking through the list, or pressing Ctrl+F and searching for it.</p>
    <p>Admins can delete items in bulk on the admin panel, and can bypass the daily delete limit, or disable yours. You should contact an admin if you need help with this.</p>
</div>
</body>
</html>

bills/templates/bills/house_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deleting {{ house.house_name }}</title>
</head>
<body>
     {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top: 12px;" align="center">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ house.house_name }}"?</p>
            <p>Deleting a house will cause <strong>all of its bills to disappear.</strong></p>
            <p>This should <strong>only</strong> be done with the approval of an admin.</p>
            <p>Before doing this, all bills should be transferred, if they need to be kept.</p>
            <p>This action <strong>cannot be undone</strong>.</p>
            <p></p>
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
    </div>
</body>
</html>

bills/templates/bills/housedetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ house.house_name }} Bills List</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top:12px;">
        <img src="{{ house.logo_url}}" width="auto" height="150px" class="d-inline float-right" />
        {% if user.is_authenticated %}<p style="display: inline; float: right;"><a href="{% url 'bills:houseupdate' house.pk %}">Edit house</a></p>{% endif %}
        <h1>{{ house.house_name }}</h1>
        <h2>Details</h2>
        <p>Total Bills: <strong>{{ bill_count }}</strong></p>
    <h2>Bills</h2>
    {% if bill_list %}
    <div class="table-responsive table-bordered table-hover">
        <table class="table" style="margin-bottom: 0px;">
            <thead class="thead-light">
                <tr>
                    <th style="width:80%;">Name</th>
                    <th>Year</th>
                </tr>
            </thead>
            <tbody>
                {% for bill in bill_list %}
                <tr>
                    <td><a href="{% url 'bills:detail' bill.pk %}">{{ bill.bill_house.house_code }}. {{ bill.bill_number|stringformat:"03d" }} - {{ bill.bill_name }}</a></td>
                    <td>{{ bill.date_first_posted.year }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <p>There are no bills available.</p>
    {% endif %}
    </div>
</body>
</html>

bills/templates/bills/houselist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>House List</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top:12px;">
    <h1>Houses</h1>
    {% if house_list %}
    {% if user.is_authenticated %}<p style="display: inline; float: right;"><a href="{% url 'bills:housecreate' %}">Add house</a></p>{% endif %}
    <div class="table-responsive table-bordered table-hover">
        <table class="table" style="margin-bottom: 0px;">
            <tbody>
                {% for house in house_list %}
                <tr>
                    <td><a href="{% url 'bills:housedetail' house.pk %}">{{ house.house_name }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <p>There are no houses available.</p>
    {% endif %}
    </div>
</body>
</html>

bills/templates/bills/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ModelUSGov Archives</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top: 12px;">
        <div class="jumbotron">
           <h1>ModelUSGov Legislation Archives</h1>
           <p>All legislation from <a href="//reddit.com/r/ModelUSGov">ModelUSGov</a> is archived here.</p>
           <p><a class="btn btn-primary" role="button" href="{% url 'bills:list' %}">View Bills</a></p>
        </div>
    </div>
</body>
</html>

bills/templates/bills/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bills List</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <div class="container" style="margin-top:12px;">
    <h1>Bills</h1>
    {% if bill_list %}
    {% if user.is_authenticated %}<p style="display: inline; float: right;"><a href="{% url 'bills:billcreate' %}">Add bill</a></p>{% endif %}
    <div class="table-responsive table-bordered table-hover">
        <table class="table" style="margin-bottom: 0px;">
            <thead class="thead-light">
                <tr>
                    <th style="width:80%;">Name</th>
                    <th>Year</th>
                </tr>
            </thead>
            <tbody>
                {% for bill in bill_list %}
                <tr>
                    <td><a href="{% url 'bills:detail' bill.pk %}">{{ bill.bill_house.house_code }}. {{ bill.bill_number|stringformat:"03d" }} - {{ bill.bill_name }}</a></td>
                    <td>{{ bill.date_first_posted.year }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <p>There are no bills available.</p>
    {% endif %}
    </div>
</body>
</html>

bills/templates/bills/nav.html
{% load staticfiles %}
{% block nav %}
<link rel="stylesheet" href="{% static 'bills/assets/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bills/assets/fonts/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'bills/assets/css/Navigation-with-Search.css' %}">
<link rel="stylesheet" href="{% static 'bills/assets/css/styles.css' %}">

<nav class="navbar navbar-light navbar-expand-md navigation-clean-search" style="background-color:#e6eaed;">
    <div class="container"><a class="navbar-brand" href="{% url 'bills:index' %}">ModelUSGov Archives</a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navcol-1">
        <ul class="nav navbar-nav">
            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'bills:index' %}">Home</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'bills:houselist' %}">Houses</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'bills:list' %}">Bills</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="#">Resolutions</a></li>
        </ul>
    <form class="form-inline mr-auto" target="_self" method="get" action="{% url 'bills:billsearch' %}">
        <div class="form-group"><label for="search-field"><i class="fa fa-search"></i></label><input class="form-control search-field" type="search" name="q" id="search-field"></div>
    </form>
    {% if not user.is_authenticated %}
        <a class="btn btn-light action-button" role="button" href="/accounts/login?next={{ request.path }}">Login</a></div>
    {% else %}
        <a class="btn btn-light action-button" role="button" href="/accounts/logout">Logout</a></div>
    {% endif %}
    </div>
</nav>

<script src="{% static 'bills/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'bills/assets/bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}

bills/templates/bills/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit {% if bill %}Bill{% elif house %}House{% endif %} - ModelUSGov Archives</title>
</head>
<body>
    {% block nav %}
        {% include 'bills/nav.html' %}
    {% endblock %}
    <!--{ if user.is_authenticated }-->
    <div class="container" style="margin-top: 12px;" align="center">
        <h2>Editing {% if bill %}{{ bill.bill_house.house_code }}. {{ bill.bill_number|stringformat:"03d" }}{% elif house %}{{ house.house_name }}{% endif %}</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" style="background-color:#e6eaed;color:rgb(0,0,0);" value="Save">
        </form>

        {% if bill %}
            <p style="display: inline-block; margin-top: 20px;"><a style="color: #d44950;" href="{% url 'bills:billdelete' bill.pk %}">Delete bill</a></p>
        {% elif house %}
            <p style="display: inline-block; margin-top: 20px;"><a style="color: #d44950;" href="{% url 'bills:housedelete' house.pk %}">Delete house</a></p>
        {% endif %}
    </div>
    <!--ELSE-->
        <!--<meta http-equiv="REFRESH" content="0;url='/accounts/login'">-->
    <!--ENDIF-->
</body>
</html>